name: Daily check in
on:
  schedule:
    - cron: '30 6 * * *'
jobs:
  Check-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install openssl
        run: sudo apt-get install -y make libssl-dev
      
      - name: Build
        run: make
      
      - name: Run the program
        env:
          ACTION_BILI: ${{ secrets.ACTION_BILI }}
          ACTION_API: ${{ secrets.ACTION_API }}
        run: ./bili
